version: '3.7'
services:
  web:
    image: nginx:latest
    container_name: webserver
    hostname: webserver
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - php
      - database
      - redis
    volumes:
      - ./www:/application
      - ./src/site.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx/
    networks:
      - infra      

  database:
    image: jacobalberty/firebird
    container_name: firebird
    hostname: firebird
    ports:
       - 3050:3050
    restart: always
    volumes:
      - ./database:/database
    networks:
      - infra      
  
  redis:
    image: redis:latest      
    container_name: redisaws
    hostname: redisaws
    restart: always
    networks:
      - infra      
  
  php:
    image: php:7.4-fpm
    container_name: php74aws
    hostname: php74aws
    ports:
      - 9000
    restart: always
    volumes:
      - ./www:/usr/share/nginx/html/
      - ./php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - infra      

networks:
  infra:
    driver: bridge

